### ISSUE TITLE
Exercise 5 Task 1 - Please clarify if it is a Pooled or a Personal desktop host pool

### ISSUE THREAD

**Issue by NehaTF** [microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise#6]
In Exercise 5, as per the Task 1 header, we need to create a **personal** desktop host pool. Whereas the task description specifies the creation of **pooled** desktop host pool.
Host pool creation screenshot specifies a picture with **Personal** selected. But as per the instructions, the required OS image is Windows 10 Enterprise multisession + M365 apps. This OS image option is available only for **Pooled** desktop and not for **Personal** desktop.
So, please clarify if we need to create a Personal or a Pooled desktop host pool in Exercise 5.

**Comment by dwnatwick** [comment]
@NehaTF Thank you for pointing this out.  This appears to be an error in the screenshot provided, since, as you pointed out, the image is only available in a pooled desktop.  We are in the process right now of doing some updates/enhancements to this workshop and we will get this screenshot fixed within the process.  Have a great day.

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #9
